name: /mnt/usrc-storage-nfs/adaml/ldyken/envs/image-gaussian
channels:
  - pytorch
  - nvidia
  - nvidia/label/cuda-12.4.0
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - binutils=2.40=h1680402_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.9=hbd8a1cb_0
  - cccl=2.3.2=h2c7f797_0
  - cuda=12.4.0=0
  - cuda-cccl=12.4.127=h06a4308_2
  - cuda-cccl_linux-64=12.4.127=h06a4308_2
  - cuda-command-line-tools=12.4.1=h06a4308_1
  - cuda-compiler=12.4.1=h6a678d5_1
  - cuda-crt-dev_linux-64=12.4.131=h06a4308_0
  - cuda-crt-tools=12.4.131=h06a4308_0
  - cuda-cudart=12.4.127=h99ab3db_0
  - cuda-cudart-dev=12.4.127=h99ab3db_0
  - cuda-cudart-dev_linux-64=12.4.127=hd681fbe_0
  - cuda-cudart-static=12.4.127=h99ab3db_0
  - cuda-cudart-static_linux-64=12.4.127=hd681fbe_0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-cuobjdump=12.4.127=h6a678d5_1
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-cupti-dev=12.4.127=h6a678d5_1
  - cuda-cuxxfilt=12.4.127=h6a678d5_1
  - cuda-demo-suite=12.4.99=0
  - cuda-driver-dev=12.4.127=h99ab3db_0
  - cuda-driver-dev_linux-64=12.4.127=hd681fbe_0
  - cuda-gdb=12.4.127=h122497a_1
  - cuda-libraries=12.4.1=h06a4308_1
  - cuda-libraries-dev=12.4.1=h06a4308_1
  - cuda-nsight=12.4.127=h06a4308_1
  - cuda-nvcc=12.4.131=h02f8991_0
  - cuda-nvcc-dev_linux-64=12.4.131=h4ee8466_0
  - cuda-nvcc-impl=12.4.131=h99ab3db_0
  - cuda-nvcc-tools=12.4.131=h99ab3db_0
  - cuda-nvcc_linux-64=12.4.131=he92618c_0
  - cuda-nvdisasm=12.4.127=h6a678d5_1
  - cuda-nvml-dev=12.4.127=h6a678d5_1
  - cuda-nvprof=12.4.127=h6a678d5_1
  - cuda-nvprune=12.4.127=h6a678d5_1
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-nvrtc-dev=12.4.127=h99ab3db_1
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-nvvm-dev_linux-64=12.4.131=h06a4308_0
  - cuda-nvvm-impl=12.4.131=h6a678d5_0
  - cuda-nvvm-tools=12.4.131=h6a678d5_0
  - cuda-nvvp=12.4.127=h6a678d5_1
  - cuda-opencl=12.4.127=h6a678d5_0
  - cuda-opencl-dev=12.4.127=h6a678d5_0
  - cuda-profiler-api=12.4.127=h06a4308_1
  - cuda-runtime=12.4.1=0
  - cuda-sanitizer-api=12.4.127=h99ab3db_1
  - cuda-toolkit=12.4.1=hb982923_0
  - cuda-tools=12.4.1=h06a4308_1
  - cuda-version=12.4=hbda6634_3
  - cuda-visual-tools=12.4.1=h06a4308_1
  - dbus=1.13.18=hb2f20db_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.13.3=h4a9f257_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gds-tools=1.9.1.3=h99ab3db_1
  - glib=2.84.2=h6a678d5_0
  - glib-tools=2.84.2=h6a678d5_0
  - gmp=6.3.0=h6a678d5_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - icu=73.1=h6a678d5_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcublas=12.4.5.8=h99ab3db_1
  - libcublas-dev=12.4.5.8=h99ab3db_1
  - libcufft=11.2.1.3=h99ab3db_1
  - libcufft-dev=11.2.1.3=h99ab3db_1
  - libcufile=1.9.1.3=h99ab3db_1
  - libcufile-dev=1.9.1.3=h99ab3db_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurand-dev=10.3.5.147=h99ab3db_1
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusolver-dev=11.6.1.9=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libcusparse-dev=12.3.1.170=h99ab3db_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=12.2.0=h65d4601_19
  - libglib=2.84.2=h37c7471_0
  - libgomp=12.2.0=h65d4601_19
  - libiconv=1.16=h5eee18b_3
  - libmpdec=4.0.0=h5eee18b_0
  - libnpp=12.2.5.30=h99ab3db_1
  - libnpp-dev=12.2.5.30=h99ab3db_1
  - libnvfatbin=12.4.127=h7934f7d_2
  - libnvfatbin-dev=12.4.127=h7934f7d_2
  - libnvjitlink=12.4.127=h99ab3db_1
  - libnvjitlink-dev=12.4.127=h99ab3db_1
  - libnvjpeg=12.3.1.117=h6a678d5_1
  - libnvjpeg-dev=12.3.1.117=h06a4308_1
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - ncurses=6.4=h6a678d5_0
  - nsight-compute=2024.1.1.4=h968f9c8_2
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openssl=3.3.1=h4bc722e_2
  - pcre2=10.42=hebb0a14_1
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.13.5=h4612cfd_100_cp313
  - python_abi=3.13=0_cp313
  - pytorch-cuda=12.4=hc786d27_7
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py313h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tk=8.6.14=h993c535_1
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py313h06a4308_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - asttokens==3.0.0
      - black==24.4.2
      - certifi==2025.7.9
      - charset-normalizer==3.4.2
      - click==8.2.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - diff-gaussian-rasterization==0.0.0
      - distro==1.9.0
      - einops==0.8.0
      - executing==2.2.0
      - filelock==3.18.0
      - fonttools==4.58.5
      - fsspec==2025.5.1
      - gpumeshsampling==0.0.0
      - icecream==2.1.3
      - idna==3.10
      - imageio==2.37.0
      - jinja2==3.1.6
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - kornia==0.7.0
      - lazy-loader==0.4
      - llvmlite==0.44.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - networkx==3.5
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opencv-python==4.12.0.88
      - openexr==3.3.5
      - packaging==25.0
      - pathspec==0.12.1
      - pillow==11.3.0
      - piq==0.8.0
      - platformdirs==4.3.8
      - plyfile==1.1.2
      - pooch==1.8.2
      - pybind11==3.0.0
      - pyexr==0.4.0
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - pyvista==0.45.2
      - requests==2.32.4
      - scikit-build==0.18.1
      - scikit-image==0.25.2
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - scooby==0.10.1
      - simple-knn==0.0.0
      - six==1.17.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2025.6.11
      - torch==2.7.1
      - torchaudio==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - triton==3.3.1
      - typing-extensions==4.14.1
      - urllib3==2.5.0
      - vtk==9.4.2
prefix: /mnt/usrc-storage-nfs/adaml/ldyken/envs/image-gaussian
